<a href="https://colab.research.google.com/github/qazakhi515/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data = {
    'cars': ["BMW", "Volvo", "KIA", "Hyundai", "Mazda", "Ford"],
    'counts': [3, 4, 9, 2, 5, 1]
}

df = pd.DataFrame(data)
print(df)

      cars  counts
0      BMW       3
1    Volvo       4
2      KIA       9
3  Hyundai       2
4    Mazda       5
5     Ford       1

In [ ]:
df.head()

      cars  counts
0      BMW       3
1    Volvo       4
2      KIA       9
3  Hyundai       2
4    Mazda       5

In [ ]:
df.tail(-1)

      cars  counts
1    Volvo       4
2      KIA       9
3  Hyundai       2
4    Mazda       5
5     Ford       1

In [ ]:
df.shape

(6, 2)

In [ ]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
df.describe() #std standard deviation bu  bir biriga oxshashlik 0 bolsa hammasi bir xil. % 25 esa 2.25dan kichik yokida 2,25 ga teng.

         counts
count  6.000000
mean   4.000000
std    2.828427
min    1.000000
25%    2.250000
50%    3.500000
75%    4.750000
max    9.000000

In [ ]:
df.iloc[2:] #2- dan boahlab hammasini chiqarib beradi

      cars  counts
2      KIA       9
3  Hyundai       2
4    Mazda       5
5     Ford       1

In [ ]:
df.loc[2:5, "cars"]

2        KIA
3    Hyundai
4      Mazda
5       Ford
Name: cars, dtype: object

In [ ]:
df[df["counts"] >= 3]

    cars  counts
0    BMW       3
1  Volvo       4
2    KIA       9
4  Mazda       5

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.to_excel("saqlangan.xlsx")

In [6]:
# Series = > 1 D
cars = pd.Series (["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object